backend:
  name: git-gateway
  branch: main

local_backend: true
display_url: localhost:8000/

media_folder: content/
public_folder: static/images

collections:
  - name: 'terms-of-use'
    label: 'Terms of Use'
    folder: 'content/footer-info'
    create: true
    media_folder: ''
    public_folder: ''
    path: 'terms/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'security'
    label: 'Security Statement'
    folder: 'content/footer-info'
    create: true
    media_folder: ''
    public_folder: ''
    path: 'security/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'privacy'
    label: 'Privacy Statement'
    folder: 'content/footer-info'
    create: true
    media_folder: ''
    public_folder: ''
    path: 'privacy/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'acceptable-use'
    label: 'Acceptable Use'
    folder: 'content/footer-info'
    create: true
    media_folder: ''
    public_folder: ''
    path: 'acceptable/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'cookies-policy'
    label: 'Cookies Policy'
    folder: 'content/footer-info'
    create: true
    media_folder: ''
    public_folder: ''
    path: 'cookies/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
